ci: Add missing coverage requirements and configuration
This commit fixes error like this one:

  ERROR: usage: setup.py [options] [file_or_dir] [file_or_dir] [...]
  setup.py: error: unrecognized arguments: --cov --cov-report